export let Accoessories = {
    heading: "Home Accoessories",
    btn: ["All Home Accoessories", "Seasonal Decor", "Decorative Pillows", "Stationary", "Home Fragrance"],
    para: "Our collection contains work from emerging talent and internationally recognized designers. Together, we create A Life Extraordinary.",

    productData: [

        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FHome-Fragrance%2FRoom%20Fragrance%20Devine%20Dreams%2Fimage-thumb__54113__header_fullscreen_2x_jpg%2Froom-spray-divine-dreams-reed-diffuser-V2.webp&w=828&q=80",
            name: "Room Fragrance Divine Dreams",
            price: "",
            type: "home",
            heading: "Room Fragrance Divine Dreams",
            Para: "Like dozing away during the lazy hours basking in the afternoon sun. Divine Dreams Room Fragrance is a warm and romantic fragrance that feels like a sweet dream you never want to end. Discover a room …",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Fassets%2FCollection%2FHome-Fragrance%2FRoom%2520Fragrance%2520Defy%2520Gravity%2Froom-spray-defy-gravity-spray-V2.png&w=828&q=80",
            name: "Room Fragrance Defy Gravity",
            price: "",
            type: "home",
            heading: "Room Fragrance Defy Gravity",
            Para: "Clear your mind and opt for a fresh start every day with Defy Gravity. With rare ambergris, Australian sandalwood, seaweeds, driftwood and African buchu. The crisp marine notes in Defy Gravity brings …",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Fassets%2FCollection%2FHome-Fragrance%2FRoom%2520Fragrance%2520Paper%2520Play%2Froom-spray-paper-play-spray-V2.png&w=828&q=80",
            name: "Room Fragrance Paper Play",
            price: "",
            type: "home",
            heading: "Room Fragrance Paper Play",
            Para: "Like entering an old library or your favourite bookstore in autumn, Paper Play is a warm and enveloping fragrance that conjures up a feeling of nostalgia. A Home Fragrance that feels as if rifling thr…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Fassets%2FCollection%2FHome-Fragrance%2FRoom%2520Fragrance%2520Beauty%2520Blooms%2Froom-spray-beauty-blooms-spray-V2.png&w=828&q=80",
            name: "Room Fragrance Beauty Blooms",
            price: "",
            type: "home",
            heading: "Room Fragrance Beauty Blooms",
            Para: "Imagine yourself floating through endless fields of pink pastel blossoms with Beauty Blooms. A home fragrance that makes you feel pampered and ready for a new day. Beauty Blooms is a complex fragrance…",
        },
        {
            img: "https://moooi.centracdn.net/client/dynamic/images/990_59eaa160dc.jpg",
            name: "Moooi x EveryHuman Gift Set",
            price: "",
            type: "home",
            heading: "Moooi x EveryHuman Gift Set",
            Para: "Treat yourself or a loved one with a scent-sational gift! The Moooi X EveryHuman gift set comprises three exclusive 10ml room fragrances, Milk & Cookies, Evergreen Dream, and Night Watch, that wil…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FEvery%20Human%2Fimage-thumb__65854__header_fullscreen_2x_jpg%2FEvery-Human-Bottle-L-White-sticks.webp&w=1080&q=80",
            name: "Room Fragrance Kissing Booth",
            price: "",
            type: "home",
            heading: "Room Fragrance Kissing Booth",
            Para: "Experience the blissful joy of a first kiss with Kissing Booth by Moooi X EveryHuman. This fragrance from the Moooi X EveryHuman scent library is a juicy garden of sweet innocent bliss brimming with t…",
        },

        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Fassets%2FCollection%2FExtinct%2520Animals%2520Ornaments%2FMoooi-Armoured-Boar-Ornaments.png&w=828&q=80",
            name: "Extinct Animals Ornaments",
            price: "",
            type: "home",
            heading: "Extinct Animals Ornaments",
            Para: "It’s the season to be jolly! The Extinct Animals Ornaments are sure to bring a smile to your face. Discover the Dwarf Rhino, Dodo Pavone, Bearded Leopard, Blushing Sloth, Armoured Boar, and Indigo Mac…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FMonster%20Basketball%2FMonster%20Basketball%20Pink%2Fimage-thumb__66949__header_fullscreen_2x_jpg%2FMoooi-Monster-Basketball-Pink-Rotation-background-image.webp&w=828&q=80",
            name: "Monster Basketball",
            price: "",
            type: "home",
            heading: "Monster Basketball",
            Para: "Shoot some hoops or put it on display. In collaboration with Spalding, Marcel Wanders created the Monster Basketball. The perfect collectible for basketball fans and lovers of unexpected design. The b…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FDecorative%20Pillows%2FMenagerie-Pillows%2Fimage-thumb__54023__header_fullscreen_2x_jpg%2FMenagerie-pilllow-Square_Raven-front_Topshot.webp&w=828&q=80",
            name: "Menagerie of Extinct Animals Decorative Pillow",
            price: "",
            type: "home",
            heading: "Menagerie of Extinct Animals Decorative Pillow",
            Para: "The Menagerie of Extinct Animals decorative pillow is part of the Extinct Animal Pillows and adds a comfortable and personal touch to your sofa, chair, bed, yoga mat, you name it. The pillowcase depic…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FDecorative%20Pillows%2FFlying%20Coral%20Fish%20Pillow%2Fimage-thumb__53863__header_fullscreen_2x_jpg%2FFlying-Coral-Fish-pillow_Blue-front_Topshot.webp&w=828&q=80",
            name: "Flying Coral Fish Decorative Pillow",
            price: "",
            type: "home",
            heading: "Flying Coral Fish Decorative Pillow",
            Para: "The Flying Coral Fish decorative pillow is part of Moooi’s Extinct Animals bedding collection. This 100% raw silk decorative pillow is inspired by the Flying Coral Fish, an extinct animal that most re…",
        },

        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBlow%20Away%20Vase%2F1311%2Fimage-thumb__1311__header_fullscreen_2x_jpg%2FBlow-away-Vase-front.webp&w=828&q=80",
            name: "Blow Away Vase",
            price: "",
            type: "home",
            heading: "Blow Away Vase",
            Para: "The Blow Away is a classic Royal Blue Delft porcelain vase that experienced something truly bizarre… it has been blown aside by a powerful gush of wind. The beauty of the vase lays in the fact that it…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FThe%20Killing%20of%20the%20Piggy%20Bank%2F1648%2Fimage-thumb__1648__header_fullscreen_2x_jpg%2Fkilling-of-the-piggy-bank-3.webp&w=828&q=80",
            name: "The Killing of the Piggy Bank",
            price: "",
            type: "home",
            heading: "The Killing of the Piggy Bank",
            Para: "The Killing of the Piggy Bank represents a digital age of currency and the approach to extinction for physical money. The vase illustrates the exact moment the piggy bank is struck. The Killing of the…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Fassets%2FCollection%2FPillows%2FRendezvous%2520Tokyo%2520Blue%2520Pillow%2FRendezvous-Tokyo-Blue-Indigo-Pillowcase-square-front.png&w=828&q=80",
            name: "Rendezvous Tokyo Blue Pillow",
            price: "",
            type: "home",
            heading: "Rendezvous Tokyo Blue Pillow",
            Para: "The Rendezvous Tokyo Blue pillow is part of the Extinct Animal Pillows and adds a comfortable and personal touch to your sofa, chair, bed, yoga mat, you name it. The rectangular pillowcase depict…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Fassets%2FCollection%2FPillows%2FMenagerie%2520of%2520EA%2520Pillow%2FMoooi-Menagerie-Pillow-black-back-calligraphy-bird.png&w=828&q=80",
            name: "Menagerie of Extinct Animals Pillow",
            price: "",
            type: "home",
            heading: "Menagerie of Extinct Animals Pillow",
            Para: "The Menagerie of Extinct Animals pillow is part of the Extinct Animal Pillows and adds a comfortable and personal touch to your sofa, chair, bed, yoga mat, you name it. The rectangular pillowcase…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FDecorative%20Pillows%2FBlooming%20Seadragon%20Pillow%2Fimage-thumb__53803__header_fullscreen_2x_jpg%2FBlooming-Seadragon-pillow_Coral-font_Topshot.webp&w=828&q=80",
            name: "Embroidered Blooming Seadragon Decorative Pillow",
            price: "",
            type: "home",
            heading: "Embroidered Blooming Seadragon Decorative Pillow",
            Para: "The Embroidered Blooming Seadragon decorative pillow is part of Moooi’s Extinct Animals bedding collection. The design is inspired by the mysterious Blooming Seadragon; an Extinct Animal that develope…",
        },
        {
            img: "https://moooi.centracdn.net/client/dynamic/images/1076_4161b7e797.jpg",
            name: "Canvas Heritage Pillow",
            price: "",
            type: "home",
            heading: "Canvas Heritage Pillow",
            Para: "The Heritage Pillows are a hymn to the rich history of the Netherlands. A beautiful contrast — the affluence of historic tales presented in a contemporary graphic fashion. Each Pillowcase is made of r…",
        },

        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FPillows%2FDenim-macaque-Pillow%2Fimage-thumb__14510__header_fullscreen_2x_jpg%2FDenim-macaque-Pillow.webp&w=1920&q=80",
            name: "Denim Indigo Macaque Pillow",
            price: "",
            type: "home",
            heading: "Denim Indigo Macaque Pillow",
            Para: "The Indigo Macaque pillow is part of the Extinct Animal Pillows and adds a comfortable and personal touch to your sofa, chair, bed, yoga mat, you name it. The rectangular pillowcase depicts two c…",
        },
    ]

}