export let wall = {
    heading: "Wall & floor",
    btn: ["All Wall & floor", "Wallcovering", "Carpets"],
    para: "Our collection contains work from emerging talent and internationally recognized designers. Together, we create A Life Extraordinary.",

    productData: [
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FLinesLinesLines%2FProduct%20Shots%2F81972%2Fimage-thumb__81972__header_fullscreen_2x_jpg%2FMoooi-Carpets-LinesLinesLines-By-Alf-Product_1.webp&w=828&q=80",
            name: "LinesLinesLines Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "LinesLinesLines Carpet",
            Para: "The enchanting LinesLinesLines Carpets are designed by eight-year-old artist Alf Bärbel Wit. Alf’s abstract patterns, reminiscent of artistic legends, create a meditative vibe with intricate details. His recognisable work brings a realm of endless discovery into a space. Alf embraces the idea of viewers walking on his art, now transformed into soft and tactile carpets that he lovingly compares to petting a cat. Available in two colourful variants.",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Fassets%2FCollection%2FCarpets%2FBisanto%2FADRIANO-Carpet.png&w=828&q=80",
            name: "Bisanto Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Bisanto Carpet",
            Para: "Carpet Adriano, by Antonio Aricó, is inspired by a mosaic in the Church of Sant’Adriano, in San Demetrio Corone, Italy. According to the myths, a charming emperor was turned into a snake by …",
        },

        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Fassets%2FCollection%2FCarpets%2FSprouts%2FSprouts-Carpet.png&w=828&q=80",
            name: "Sprouts Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Sprouts Carpet",
            Para: "For designer Kiki van Eijk imagination is the most important, yet wonderful thing in life. Her design for carpet Sprouts perfectly represents this. Inspired by daydreaming and drawing in her…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FIn%20The%20Meadow%2F37764%2Fimage-thumb__37764__header_fullscreen_2x_jpg%2FEmbryo-II-200x264-300DPI.webp&w=828&q=80",
            name: "In the Meadow Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "In the Meadow Carpet",
            Para: "The carpets of Emma Larsson’s In the Meadow collection are inspired by the never-ending wonders of nature. With whimsical and abstract shapes, the carpets depict mesmerising worlds of aquarelle art. T…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FMemento%20Moooi%20Medley%2Fimage-thumb__47858__header_fullscreen_2x_jpg%2FMemento-Moooi-Medley-Dawn-250.webp&w=828&q=80",
            name: "Memento Moooi Medley Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Memento Moooi Medley Carpet",
            Para: "he Memento Moooi Medley Carpet is a gathering of Extinct Animals known for their unique kindness and love for life. Each animal knew how to cherish each moment of their lives and lived to m…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FFlowergarden%2Fimage-thumb__40518__header_fullscreen_2x_jpg%2FFlower-Garden-Night.webp&w=828&q=80",
            name: "Flowergarden Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Flowergarden Carpet",
            Para: "The Flowergarden carpets capture an overflowing flowerbed in the hours right before and after sunset. The dramatic petals of Flowergarden Day rivals the pink skies during golden hour. Flowergarden Nig…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDonut%20Carpet%2FHeart%2Fimage-thumb__49733__header_fullscreen_2x_jpg%2FHeart-Donut.webp&w=828&q=80",
            name: "Donut Fear Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Donut Fear Carpet",
            Para: "Shine bright and live fearlessly! The Donut Fear carpet collection by Jae Yong Kim aims to bring you joy when life isn’t easy. Fun designs brought into your home in unexpected ways. Artist Jae Yong Ki…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDropshadow%20Transparant%20Background%2F14209%2Fimage-thumb__14209__header_fullscreen_2x_jpg%2FCrystal%20Brown-Design-190003.webp&w=1080&q=80",
            name: "Crystal Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Crystal Carpet",
            Para: "Looking at carpet Crystal by Ingimar Einarsson is like looking at crystals reflected by a thousand mirrors. A geometric kaleidoscope of translucent layers creates an ongoing depth. Inspired by a natur…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FTulip%2Fimage-thumb__59983__header_fullscreen_2x_jpg%2FTulip%20Mania%20Red%20Shell%20300Dpi.webp&w=828&q=80",
            name: "Tulip Mania Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Tulip Mania Carpet",
            Para: "Carpet Tulip Mania by Hilde Koenders pictures a bundle of lucid coloured petals. The carpet is inspired by Hilde Koenders' artistic work, where she feeds pigmented water to tulips.…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FMixing%20Pixels%2Fimage-thumb__61749__header_fullscreen_2x_jpg%2FMixing-Pixels-of-Scribble-I-300Dpi.webp&w=828&q=80",
            name: "Tulip Mania Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Mixing Pixels Carpet",
            Para: "Mixing Pixels is a collection of carpets by Ruben de Haas. The collection results from his playful curiosity for colours and discovering new techniques. Each design is a recreation of existing ca…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FPollination%20of%20Hortensia%2Fimage-thumb__64764__header_fullscreen_2x_jpg%2FPOLLINATION-OF-HORTENSIA-CARPET-SPRING-200x300cm-300Dpi.webp&w=828&q=80",
            name: "Pollination of Hortensia Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Pollination of Hortensia Carpet",
            Para: "The Pollination of Hortensia Carpet by Andrés Reisinger illustrates the power of transformation and growth. Each carpet in the collection captures the essence of a different season. From the vibrant b…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FMimesis%2Fimage-thumb__64859__header_fullscreen_2x_jpg%2FSEB-JANIAK%2C-Mimesis-Magnolia-Astonish-rectangle-2-300Dpi.webp&w=828&q=80",
            name: "Mimesis Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Mimesis Carpet",
            Para: "Bring the wonder of nature into your home with the Mimesis Carpet Collection by multi-disciplinary artist Seb Janiak! Inspired by the ancient Greek concept of Mimèsis,each carpet in the collection …",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Fassets%2FCollection%2FWallcovering%2Fmenagerie%2Fmoooiwallcoveringextinctanimals-menagerieofextinctanimals-mo2071-m.jpg&w=1920&q=80",
            name: "Menagerie of Extinct Animals Wallcovering",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Menagerie of Extinct Animals Wallcovering",
            Para: "A fantastic fauna print − digitally printed on soft touch textile with a non-woven backing − in which each of the 10 extinct animals is mysteriously hidden.",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Fassets%2FCollection%2FWallcovering%2Fcalligraphy%2520bird%2Fmoooiwallcoveringextinctanimals-calligraphybird-mo2011-m.jpg&w=1920&q=80",
            name: "Calligraphy Bird Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Calligraphy Bird Carpet",
            Para: "Discover deep scarlet and bright sapphire hues balanced by softer shades. The Calligraphy Bird Carpet shows the extinct animal’s colourful beauty in all its splendour. Treat your interior with this ro…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDropshadow%20Transparant%20Background%2F14206%2Fimage-thumb__14206__header_fullscreen_2x_jpg%2FCalligraphy%20Bird-Design-180010.webp&w=1920&q=80",
            name: "Calligraphy Bird Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "",
            Para: "",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDropshadow%20Transparant%20Background%2F14222%2Fimage-thumb__14222__header_fullscreen_2x_jpg%2FDodo%20Pavone-Design-180003.webp&w=1920&q=80",
            name: "Dodo Pavone Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Dodo Pavone Carpet",
            Para: "The Dodo Pavone carpet depicts a soft nest of silky textures. Reminding of a fluffy pompom of silver, beige, pink & white feathers. Dodo Pavone’s harmonious colours and textures create a sense of …",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDropshadow%20Transparant%20Background%2F14339%2Fimage-thumb__14339__header_fullscreen_2x_jpg%2FWalking%20on%20Clouds%20Dusk-Design-190020.webp&w=828&q=80",
            name: "Walking on Clouds Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Walking on Clouds Carpet",
            Para: "Carpet Walking on Clouds by Front is a collage of mixed-media clouds from different eras. The clouds have been a source of inspiration for artists for centuries. Front studied the clouds in all kinds …",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDropshadow%20Transparant%20Background%2F14368%2Fimage-thumb__14368__header_fullscreen_2x_jpg%2FScribble%20Black%20Green%20Blue_Design_150016.webp&w=828&q=80",
            name: "Scribble Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Scribble Carpet",
            Para: "Carpet Scribble by Front depicts predominantly green, red and blue chalk lines on a black background. The irregularly shaped carpet is a blown-up sketch of highly visible hand-drawn lines. Scribb…",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Fassets%2FCollection%2FCarpets%2FDropshadow%2520Transparant%2520Background%2FSpace%2520Escape%2520Carpet%2520Collection%2FElena-Salmistraro-Reptilian-300dpi.png&w=828&q=80",
            name: "Space Escape Carpet",
            price: "From € 1690",
            type: "wall&floor",
            heading: "Space Escape Carpet",
            Para: "Carpets Reptilian and Plejaren by Elena Salmistraro are part of the Space Escape collection. The carpets tell the revolutionary story of our interstellar travel…",
        },

    ]
}