export let data = {
    heading: "All Bedding & bath",
    btn: ["All Bedding & bath", "Bedding", "BSath"],
    para: "Our collection contains work from emerging talent and internationally recognized designers. Together, we create A Life Extraordinary.",

    productData: [
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FBed%20Scarf%2FMenagerie%2Fimage-thumb__51143__header_fullscreen_2x_jpg%2F6934-MO-Menagerie-of-Extinct-Animals-Raven-XL-Scarf.webp&w=1080&q=80",
            name: "Menagerie of Extinct Animals Bed Scarf XL",
            price: "From € 250",
            type: "BeddingBath",
            heading: "Menagerie of Extinct Animals Bed Scarf XL",
            Para: "The Menagerie of Extinct Animals scarf is part of the Extinct Animals bedding collection. Hang the scarf over a chair or at the end of your bed for the finishing touch to your bedroom. The scarf’s botanical print reveals a richly illustrated world brimming with life. Look closely and discover the extinct animals surrounded by the flora and fauna of their natural habitat."

        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FBedspread%2FDodo%20Pavone%2Fimage-thumb__51138__header_fullscreen_2x_jpg%2F6933-MO-Dodo-Pavone-Bedspread-Ivory.webp&w=1080&q=80",
            name: "Embroidered Dodo Pavone Bedspread",
            price: " From € 250",
            type: "BeddingBath",
            heading: "Embroidered Dodo Pavone Bedspread",
            Para: "The Embroidered Dodo Pavone bedspread is part of Moooi’s Extinct Animals bedding collection. The bedspread has a unique quilted motif inspired by the soft plumage of the amiable Dodo Pavone that lived thousands of years ago. The unique pattern in combination with the embroidered 3D effect gives the bedspread a dream-like appearance. The shiny sateen weave feels wonderfully soft and gives the bedspread a luxurious look. The bedspread is adorned with an Oxford edge.",

        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FBed%20Pillows%2FCalligraphy%20Bird%20Bed%20Pillows%2Fimage-thumb__53058__header_fullscreen_2x_jpg%2FCalligraphy-Bird_Blue_US_UV_King-2x36x20-10_Topshot-front.webp&w=1080&q=80",
            name: "Calligraphy Bird Bed Pillows",
            price: "From € 110",
            type: "BeddingBath",
            heading: "Calligraphy Bird Bed Pillows",
            Para: "The Calligraphy Bird bed pillows are part of Moooi’s Extinct Animals bedding collection. The exclusive bed pillows have a subtle jacquard weave on the front, based on the smallest and softest down feathers of the extinct Calligraphy Bird. The deep colours add a modern and contemporary look. The reverse side is dyed in a solid colour and is made from 100% cotton sateen for an extra soft and smooth feeling. The pillowcases are finished with double Oxford edging. Insert not included.",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FDuvets%2FDuvets-colored-sheets%2Fimage-thumb__56613__header_fullscreen_2x_jpg%2FUmbrella-Squid_Silver_2P-10_Topshot-NEW_1.webp&w=1080&q=80",
            name: "Umbrella Squid Duvet Cover Set",
            price: "From € 250",
            type: "BeddingBath",
            heading: "Umbrella Squid Duvet Cover Set",
            Para: "The Umbrella Squid duvet cover set is part of the Extinct Animals bedding collection. The subtle jacquard weave on the duvet cover set depicts the magical skin of the Umbrella Squid, which was covered with luminous jewels that changed colour. Light and shadow alternated gracefully in a magical underwater world of movement and colour. The reverse side is dyed in a solid colour. The pillowcases feature an Oxford edging with decorative cord piping. The Umbrella Squid duvet cover set is made from 100% cotton sateen for an extra soft and smooth feeling.",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FDuvets%2FDuvets-colored-sheets%2Fimage-thumb__56623__header_fullscreen_2x_jpg%2FCalligraphy-Bird-Blue_Topshot.webp&w=1080&q=80",
            name: "Calligraphy Bird Duvet Cover Set",
            price: "From € 250",
            type: "BeddingBath",
            heading: "Calligraphy Bird Duvet Cover Set",
            Para: "The Calligraphy Bird duvet cover set is part of the Extinct Animals bedding collection. The exclusive duvet cover set has a subtle jacquard weave on the front, based on the smallest and softest down feathers of the extinct Calligraphy Bird. The deep colours add a modern and contemporary look. The reverse side is dyed in a solid colour. The pillowcases feature double Oxford edging. The pillowcases and reverse side of the duvet cover set are made from 100% cotton sateen for an extra soft and smooth feeling. ",

        },
        {
            img: "https://moooi.centracdn.net/client/dynamic/images/784_85fdde1766.jpg",
            name: "Embroidered Dodo Pavone Duvet Cover Set",
            price: "From € 270",
            type: "BeddingBath",
            heading: "Embroidered Dodo Pavone Duvet Cover Set",
            Para: "The Embroidered Dodo Pavone duvet cover set is part of the Extinct Animals bedding collection. This exclusive duvet cover set has a unique quilted motif inspired by the characteristics of the now extinct Dodo Pavone – the largest bird to ever exist on the island of Mauritius. The dreamy pattern in combination with the embroidered 3D effect makes your bedroom the most luxurious room in your home. The backs of the duvet cover and the pillowcases have a solid colour. The pillowcases feature double cord piping. ",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FDuvets%2FDuvets-colored-sheets%2Fimage-thumb__56638__header_fullscreen_2x_jpg%2FDodo-Pavone-Green_Topshot.webp&w=1080&q=80",
            name: "Dodo Pavone Duvet Cover Set ",
            price: "From € 210",
            type: "BeddingBath",
            heading: "Dodo Pavone Duvet Cover Set",
            Para: "The Dodo Pavone duvet cover set is part of the Extinct Animals bedding collection. This exclusive and extravagant duvet cover set has a digital print inspired by the characteristics of the now extinct Dodo Pavone – the largest bird to ever exist on the island of Mauritius. The beautiful pattern gives this bedding set a dream-like appearance. The pillowcases and back of the duvet cover is dyed in a solid colour. The pillowcases feature decorative flat piping. The shiny 100% cotton sateen weave feels wonderfully soft and gives the duvet cover a luxurious look.",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FDuvets%2FDuvets-colored-sheets%2Fimage-thumb__56643__header_fullscreen_2x_jpg%2FMenagerie-of-Extinct-Animals-Black_Topshot.webp&w=1080&q=80",
            name: "Menagerie of Extinct Animals Duvet Cover Set",
            price: "From € 240",
            type: "BeddingBath",
            heading: "Menagerie of Extinct Animals Duvet Cover Set",
            Para: "Look closely and discover a lush and richly illustrated world brimming with life. The Menagerie of Extinct Animals duvet cover set, from the Extinct Animals bedding collection, turns your bedroom into the most inviting space in the house. The reverse side of the duvet cover and pillowcases features a stylish circle pattern, inspired by the characteristics of the extinct Umbrella Squid. The pillowcases have an Oxford edge and luxurious flat piping. The shiny 100% cotton sateen weave feels wonderfully soft and gives the duvet cover set a luxurious look. ",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FBed%20Pillows%2FEmbroidered%20Dodo%20Pavone%20Bed%20Pillows%2Fimage-thumb__52978__header_fullscreen_2x_jpg%2FEmbroidered-Dodo-Pavone_White_US_UV_King-2x36x20-10_Topshot-front.webp&w=1080&q=80",
            name: "Embroidered Dodo Pavone Bed Pillows",
            price: "From € 90",
            type: "BeddingBath",
            heading: "Embroidered Dodo Pavone Bed Pillows",
            Para: "The Embroidered Dodo Pavone bed pillows are a part of Moooi’s Extinct Animals bedding collection. The exclusive bed pillows have a unique quilted motif inspired by the characteristics of the now extinct Dodo Pavone – the largest bird to ever exist on the island of Mauritius. The dreamy pattern in combination with the embroidered 3D effect makes your bedroom the most luxurious room in your home. The backs of the bed pillows have a solid colour. The bed pillows feature cord piping. Insert not included. ",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FBed%20Pillows%2FDodo%20Pavone%20Bed%20Pillows%2Fimage-thumb__52998__header_fullscreen_2x_jpg%2FDodo-Pavone_Green_US_UV_King-2x36x20-10_Topshot-front.webp&w=1080&q=80",
            name: "Dodo Pavone Bed Pillows",
            price: "From € 85",
            type: "BeddingBath",
            heading: "Dodo Pavone Bed Pillows",
            Para: "The Dodo Pavone bed pillows are part of Moooi’s Extinct Animals bedding collection. These exclusive and extravagant bed pillows have a digital print inspired by the characteristics of the now extinct Dodo Pavone – the largest bird to ever exist on the island of Mauritius. The beautiful pattern gives the bed pillows a dream-like appearance. The back is dyed in a solid colour. The soft and shiny 100% cotton sateen weave and decorative flat piping give the bed pillows a luxurious look. ",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FBed%20Pillows%2FUmbrella%20Squid%20Bed%20Pillows%2Fimage-thumb__53048__header_fullscreen_2x_jpg%2FUmbrella-Squid_Silver_US_UV_King-2x36x20-10_Topshot-front.webp&w=1080&q=80",
            name: "Umbrella Squid Bed Pillows",
            price: "From € 100",
            type: "BeddingBath",
            heading: "Umbrella Squid Bed Pillows",
            Para: "The Umbrella Squid bed pillows are part of Moooi’s Extinct Animals bedding collection. The subtle jacquard weave on the bed pillows depicts the magical skin of the Umbrella Squid, which was covered with luminous jewels that changed colour. Light and shadow alternated gracefully in a magical underwater world of movement and colour. The reverse side is dyed in a solid colour. The Umbrella Squid bed pillows are made from 100% cotton sateen for an extra soft and smooth feeling. ",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FBed%20Pillows%2FMenagerie%20Bed%20Pillows%2Fimage-thumb__53078__header_fullscreen_2x_jpg%2FMenagerie_Raven_US_UV_King-2x36x20-10_Topshot-front.webp&w=1080&q=80",
            name: "Menagerie of Extinct Animals Bed Pillows",
            price: "From € 120",
            type: "BeddingBath",
            heading: "Menagerie of Extinct Animals Bed Pillows",
            Para: "Look closely and discover a lush and richly illustrated world brimming with life. The Menagerie of Extinct Animals bed pillows, from the Moooi Extinct Animals bedding collection, turn your bedroom into the most inviting space in the house. The pillowcases have an Oxford edge and luxurious flat piping. The shiny 100% cotton sateen weave feels wonderfully soft and gives the pillow cases a luxurious look. Pillow insert not included. ",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBath%2FTowel%2Fimage-thumb__65444__header_fullscreen_2x_jpg%2FDodo-Pavone-Towel_Stack-Topshot.webp&w=1080&q=80",
            name: "Dodo Pavone Towel",
            price: "From € 120",
            type: "BeddingBath",
            heading: "Dodo Pavone Towel",
            Para: "Enhance your bathroom décor with the stylish and luxurious Dodo Pavone Towels. The high-quality towel features a unique jacquard woven pattern inspired by the feathers of the Dodo Pavone. The dreamy pattern combined with woven edges at the top and bottom give the towel a luxurious feel. The towel has a woven loop for easy hanging. Available as a guest towel, hand towel, bath towel, and bath sheet in different colours. Each towel is sold individually. ",
        },

        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBath%2FBeach%20Towel%2Fimage-thumb__64384__header_fullscreen_2x_jpg%2FMenagerie-Beach-towel_Ivory_UV_UV_100x180-10_Topshot.webp&w=1080&q=80",
            name: "Menagerie of Extinct Animals Beach Towel",
            price: "From € 140",
            type: "BeddingBath",
            heading: "Menagerie of Extinct Animals Beach Towel",
            Para: "Get ready for the beach in seconds! The Menagerie of Extinct Animals beach towel features an exotic and botanical motif inspired by sketches of now-extinct animals. The motif is printed on a jacquard woven pattern, making the towel wonderfully soft. The motif conveys an enchanting depth and mysticism, thanks to the vivid colours in the coats and feathers of the extinct animals. This is further emphasised by the jacquard pattern. The beach towel has a woven border at the top and bottom. The towel has a woven loop for easy hanging. ",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBath%2FKimono%2Fimage-thumb__64209__header_fullscreen_2x_jpg%2FMenagerie-Kimono_Raven_UV_UV--L-10_Topshot.webp&w=1080&q=80",
            name: "Menagerie of Extinct Animals Kimono",
            price: "From € 180",
            type: "BeddingBath",
            heading: "Menagerie of Extinct Animals Kimono",
            Para: "Whether you’re lounging, bathing, at the beach or pool, your day is not complete without a stylish cover-up. With the Menagerie of Extinct Animals kimono, you can wrap yourself in style. The kimono has a luxurious look with its shawl collar, cuffs, and belt with round piping. The Kimono has hidden pockets on both sides and features a woven hang loop. The kimono is made from 100% cotton with a sateen weave that feels wonderfully soft and smooth on your skin. The menagerie motif, available in two colours, depicts a colourful botanical world. Hidden among the plants and flowers, you will find several Extinct Animals. Available in two colours. ",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBath%2FBathrobe%2Fimage-thumb__64219__header_fullscreen_2x_jpg%2FDodo-Pavone-Bathrobe_White_UV_UV-10_Topshot.webp&w=1080&q=80",
            name: "Dodo Pavone Bathrobe",
            price: "From € 280",
            type: "BeddingBath",
            heading: "Dodo Pavone Bathrobe",
            Para: "Bring on those lazy Sundays with the Dodo Pavone bathrobe. The high-quality 100% cotton bathrobe features a unique jacquard woven pattern inspired by the feathers of the largest, now extinct bird on the island of Mauritius, the Dodo Pavone. The bathrobe has a shawl collar and sleeves in wonderfully soft and chic shiny cotton velvet which are finished with piping. The bathrobe has pockets on both sides and features a woven hang loop. The dreamy pattern combined with luxurious finish gives your day a botanical touch. Available in two colours. ",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBath%2FTowel%2FMenagerie%20of%20Extinct%20Animals%20Towel%2Fimage-thumb__64294__header_fullscreen_2x_jpg%2FMenagerie-Towel_Ivory_UV_UV_100x150-10_Topshot.webp&w=1080&q=80",
            name: "Menagerie of Extinct Animals Towel",
            price: "From € 180",
            type: "BeddingBath",
            heading: "Menagerie of Extinct Animals Towel",
            Para: "The Menagerie of Extinct Animals towel transform your bathroom to a botanical spa. The motif is printed on a jacquard woven cotton, making it feel extra soft and comfortable. Look closely and discover a lush and richly illustrated green world brimming with life. Each towel has a woven border at the top and bottom and a loop for easy hanging. Transform your daily bathroom routine into a pampering experience with the Menagerie of Extinct Animals towels. Available as a guest towel, hand towel, bath towel, and bath sheet. Each towel is sold individually.  ",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FFitted%20Sheets%2FMenagerie%2Fimage-thumb__52883__header_fullscreen_2x_jpg%2FMenagerie_Green_US_UV_Mood_1.webp&w=1080&q=80",
            name: "Menagerie of Extinct Animals Fitted Sheet",
            price: "From € 180",
            type: "BeddingBath",
            heading: "Menagerie of Extinct Animals Fitted Sheet",
            Para: "The Menagerie of Extinct Animals fitted sheet is part of the Moooi Extinct Animals bedding collection. Menagerie of Extinct Animals is an exclusive fitted sheet made of 100% high-quality cotton sateen, 300 TC. The deep green colour adds a luxurious and contemporary look to the fitted sheet. The fitted sheet is elasticised around the entire perimeter and fits mattresses up to 18 inches. ",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FFitted%20Sheets%2FEmbroidered%20Dodo%2Fimage-thumb__52478__header_fullscreen_2x_jpg%2FEmbroidered-Dodo_Ivory_US_UV_Mood.webp&w=1080&q=80",
            name: "Embroidered Dodo Pavone Fitted Sheet",
            price: "From € 180",
            type: "BeddingBath",
            heading: "Embroidered Dodo Pavone Fitted Sheet",
            Para: "The Embroidered Dodo Pavone fitted sheet is part of the Moooi Extinct Animals bedding collection. Embroidered Dodo Pavone is an exclusive fitted sheet made of 100% high-quality cotton sateen, 230 TC. The luxurious ivory colour adds a sophisticated and contemporary look to the fitted sheet. The fitted sheet is elasticised around the entire perimeter and fits mattresses up to 18 inches. ",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FFitted%20Sheets%2FUmbrella%20Squid%2Fimage-thumb__52483__header_fullscreen_2x_jpg%2FUmbrella-Squid_Silver_US_UV_Mood.webp&w=1080&q=80",
            name: "Umbrella Squid Fitted Sheet",
            price: "From € 120",
            type: "BeddingBath",
            heading: "Umbrella Squid Fitted Sheet",
            Para: "The Umbrella Squid fitted sheet is part of the Moooi Extinct Animals bedding collection. Umbrella Squid is an exclusive fitted sheet made of 100% high-quality cotton sateen, 300 TC. The silver colour adds a sophisticated and contemporary look to the fitted sheet. The fitted sheet is elasticised around the entire perimeter and fits mattresses up to 18 inches. ",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FFitted%20Sheets%2FDodo%20Pavone%2Fimage-thumb__52493__header_fullscreen_2x_jpg%2FDodo-Pavone_Dark-Sand_US_UV_Mood.webp&w=1080&q=80",
            name: "Dodo Pavone Fitted Sheet",
            price: "From € 180",
            type: "BeddingBath",
            heading: "Dodo Pavone Fitted Sheet",
            Para: "The Dodo Pavone fitted sheet is part of the Moooi Extinct Animals bedding collection. Dodo Pavone is an exclusive fitted sheet made of 100% high-quality cotton sateen, 300 TC. The deep colours add a luxurious and contemporary look to the fitted sheet. The fitted sheet is elasticised around the entire perimeter and fits mattresses up to 18 inches. ",
        },
        {
            img: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FFitted%20Sheets%2FCalligraphy%20Bird%2Fimage-thumb__52468__header_fullscreen_2x_jpg%2FCalligraphy-Bird_Blue_US_UV_Mood.webp&w=1080&q=80",
            name: "Calligraphy Bird Fitted Sheet",
            price: "From € 120",
            type: "BeddingBath",
            heading: "Calligraphy Bird Fitted Sheet",
            Para: "The Calligraphy Bird fitted sheet is part of the Moooi Extinct Animals bedding collection. Calligraphy Bird is an exclusive fitted sheet made of 100% high-quality cotton sateen, 300 TC. The deep blue colour adds a sophisticated and contemporary look to the fitted sheet. The fitted sheet is elasticised around the entire perimeter and fits mattresses up to 18 inches.",
        },
    ]
}